carriers = {
  "3 River Wireless": "sms.3rivers.net",
  "ACS Wireless": "paging.acswireless.com",
  "Alltel": "message.alltel.com",
  "AT&T": "mobile.att.net",
  "Bell Canada": "bellmobility.ca",
  "Bell Mobility (Canada)": "txt.bell.ca",
  "Bell Mobility": "txt.bellmobility.ca",
  "Blue Sky Frog": "blueskyfrog.com",
  "Bluegrass Cellular": "sms.bluecell.com",
  "Boost Mobile": "myboostmobile.com",
  "BPL Mobile": "bplmobile.com",
  "Carolina West Wireless": "cwwsms.com",
  "Cellular One": "sbcemail.com",
  "Cellular South": "csouth1.com",
  "Centennial Wireless": "cwemail.com",
  "CenturyTel": "messaging.centurytel.net",
  "Cingular (Now AT&T)": "txt.att.net",
  "Clearnet": "msg.clearnet.com",
  "Comcast": "comcastpcs.textmsg.com",
  "Corr Wireless Communications": "corrwireless.net",
  "Dobson": "mobile.dobson.net",
  "Edge Wireless": "sms.edgewireless.com",
  "Fido": "fido.ca",
  "Golden Telecom": "sms.goldentele.com",
  "Helio": "messaging.sprintpcs.com",
  "Houston Cellular": "text.houstoncellular.net",
  "Idea Cellular": "ideacellular.net",
  "Illinois Valley Cellular": "ivctext.com",
  "Inland Cellular Telephone": "inlandlink.com",
  "MCI": "pagemci.com",
  "Metrocall": "page.metrocall.com",
  "Metrocall 2-way": "my2way.com",
  "Metro PCS": "mymetropcs.com",
  "Microcell": "fido.ca",
  "Midwest Wireless": "clearlydigital.com",
  "Mobilcomm": "mobilecomm.net",
  "MTS": "text.mtsmobility.com",
  "Nextel": "page.nextel.com",
  "OnlineBeep": "onlinebeep.net",
  "PCS One": "pcsone.net",
  "President's Choice": "txt.bell.ca",
  "Public Service Cellular": "sms.pscel.com",
  "Qwest": "qwestmp.com",
  "Rogers AT&T Wireless": "pcs.rogers.com",
  "Rogers Canada": "pcs.rogers.com",
  "Satellink": "satellink.net",
  "Southwestern Bell": "email.swbw.com",
  "Sprint": "messaging.sprintpcs.com",
  "Sumcom": "tms.suncom.com",
  "Surewest Communicaitons": "mobile.surewest.com",
  "T-Mobile": "tmomail.net",
  "Telus": "msg.telus.com",
  "Tracfone": "txt.att.net",
  "Triton": "tms.suncom.com",
  "Unicel": "utext.com",
  "US Cellular": "email.uscc.net",
  "Solo Mobile": "txt.bell.ca",
  "US West": "uswestdatamail.com",
  "Verizon": "vtext.com",
  "Virgin Mobile": "vmobl.com",
  "Virgin Mobile Canada": "vmobile.ca",
  "West Central Wireless": "sms.wcc.net",
  "Western Wireless": "cellularonewest.com",
  "Chennai RPG Cellular": "rpgmail.net",
  "Chennai Skycell \/ Airtel": "airtelchennai.com",
  "Comviq": "sms.comviq.se",
  "Delhi Aritel": "airtelmail.com",
  "Delhi Hutch": "delhi.hutch.co.in",
  "DT T-Mobile": "t-mobile-sms.de",
  "Dutchtone \/ Orange-NL": "sms.orange.nl",
  "EMT": "sms.emt.ee",
  "Escotel": "escotelmobile.com",
  "German T-Mobile": "t-mobile-sms.de",
  "Goa BPLMobil": "bplmobile.com",
  "Gujarat Celforce": "celforce.com",
  "JSM Tele-Page": "jsmtel.com",
  "Kerala Escotel": "escotelmobile.com",
  "Kolkata Airtel": "airtelkol.com",
  "Kyivstar": "smsmail.lmt.lv",
  "Lauttamus Communication": "e-page.net",
  "LMT": "smsmail.lmt.lv",
  "Maharashtra BPL Mobile": "bplmobile.com",
  "Maharashtra Idea Cellular": "ideacellular.net",
  "Manitoba Telecom Systems": "text.mtsmobility.com",
  "Meteor": "mymeteor.ie",
  "MiWorld": "m1.com.sg",
  "Mobileone": "m1.com.sg",
  "Mobilfone": "page.mobilfone.com",
  "Mobility Bermuda": "ml.bm",
  "Mobistar Belgium": "mobistar.be",
  "Mobitel Tanzania": "sms.co.tz",
  "Mobtel Srbija": "mobtel.co.yu",
  "Movistar": "correo.movistar.net",
  "Mumbai BPL Mobile": "bplmobile.com",
  "Netcom": "sms.netcom.no",
  "Ntelos": "pcs.ntelos.com",
  "O2": "o2imail.co.uk",
  "O2 (M-mail)": "mmail.co.uk",
  "One Connect Austria": "onemail.at",
  "Optus Mobile": "optusmobile.com.au",
  "Orange": "orange.net",
  "Orange Mumbai": "orangemail.co.in",
  "Orange NL \/ Dutchtone": "sms.orange.nl",
  "Oskar": "mujoskar.cz",
  "P&T Luxembourg": "sms.luxgsm.lu",
  "Personal Communication": "pcom.ru (put the number in the subject line)",
  "Pondicherry BPL Mobile": "bplmobile.com",
  "Primtel": "sms.primtel.ru",
  "Safaricom": "safaricomsms.com",
  "Satelindo GSM": "satelindogsm.com",
  "SCS-900": "scs-900.ru",
  "SFR France": "sfr.fr",
  "Simple Freedom": "text.simplefreedom.net",
  "Smart Telecom": "mysmart.mymobile.ph",
  "Southern LINC": "page.southernlinc.com",
  "Sunrise Mobile": "swmsg.com",
  "Surewest Communications": "freesurf.ch",
  "Swisscom": "bluewin.ch",
  "T-Mobile Austria": "sms.t-mobile.at",
  "T-Mobile Germany": "t-d1-sms.de",
  "T-Mobile UK": "t-mobile.uk.net",
  "Tamil Nadu BPL Mobile": "bplmobile.com",
  "Tele2 Latvia": "sms.tele2.lv",
  "Telefonica Movistar": "movistar.net",
  "Telenor": "mobilpost.no",
  "Teletouch": "pageme.teletouch.com",
  "Telia Denmark": "gsm1800.telia.dk",
  "TIM": "timnet.com",
  "TSR Wireless": "alphame.com",
  "UMC": "sms.umc.com.ua",
  "Uraltel": "sms.uraltel.ru",
  "Uttar Pradesh Escotel": "escotelmobile.com",
  "Vessotel": "pager.irkutsk.ru",
  "Vodafone Italy": "sms.vodafone.it",
  "Vodafone Japan": "t.vodafone.ne.jp",
  "Vodafone UK": "vodafone.net",
  "Wyndtell": "wyndtell.com",
  "Advantage Communications": "advantagepaging.com",
  "Airtouch Pagers": "myairmail.com",
  "AlphaNow": "alphanow.net",
  "Ameritech Paging": "paging.acswireless.com",
  "American Messaging": "page.americanmessaging.net",
  "Ameritech Clearpath": "clearpath.acswireless.com",
  "Arch Pagers (PageNet)": "archwireless.net",
  "AT&T Free2Go": "mmode.com",
  "AT&T PCS": "mobile.att.net",
  "AT&T Pocketnet PCS": "dpcs.mobile.att.net",
  "Beepwear": "beepwear.net",
  "Bell Atlantic": "message.bam.com",
  "Bell South": "wireless.bellsouth.com",
  "Bell South (Blackberry)": "bellsouthtips.com",
  "Bell South Mobility": "blsdcs.net",
  "Cellular One (East Coast)": "phone.cellone.net",
  "Cellular One (South West)": "swmsg.com",
  "Cellular One (West)": "mycellone.com",
  "Central Vermont Communications": "cvcpaging.com",
  "Cingular": "cingularme.com",
  "Communication Specialists": "pageme.comspeco.net",
  "Cook Paging": "cookmail.com",
  "Digi-Page \/ Page Kansas": "page.hit.net",
  "Galaxy Corporation": "sendabeep.net",
  "GCS Paging": "webpager.us",
  "GrayLink \/ Porta-Phone": "epage.porta-phone.com",
  "GTE": "messagealert.com",
  "Infopage Systems": "page.infopagesystems.com",
  "Indiana Paging Co": "inlandlink.com",
  "Mobilecom PA": "page.mobilcom.net",
  "Morris Wireless": "beepone.net",
  "Motient": "isp.com",
  "Omnipoint": "omnipointpcs.com",
  "Pacific Bell": "pacbellpcs.net",
  "PageMart": "pagemart.net",
  "PageMart Canada": "pmcl.net",
  "PageNet Canada": "pagegate.pagenet.ca",
  "PageOne Northwest": "page1nw.com",
  "Powertel": "voicestream.net",
  "Price Communications": "mobilecell1se.com",
  "Primeco": "email.uscc.net",
  "ProPage": "page.propage.net",
  "Qualcomm": "pager.qualcomm.com",
  "RAM Page": "ram-page.com",
  "SBC Ameritech Paging": "paging.acswireless.com",
  "Skytel Pagers": "email.skytel.com",
  "ST Paging": "page.stpaging.com",
  "Verizon Pagers": "myairmail.com",
  "Verizon PCS": "myvzw.com",
  "VoiceStream": "voicestream.net",
  "WebLink Wireless": "pagemart.net"
}

if (Meteor.isClient) {
  UI.registerHelper("carriers", function() {
    return _.map(Object.keys(carriers), function(k) {
      return {name: k, domain: carriers[k]};
    })
  });
}
